// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LinuxSSHDebugger
{
    internal sealed partial class Vsix
    {
        public const string Id = "LinuxSSHDebugger.81385f77-f4a3-43a5-a4d2-4899626e2c95";
        public const string Name = "Linux SSH Debugger";
        public const string Description = @"Linux SSH Debugger";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Kerry Jones";
        public const string Tags = "";
    }
}
