// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LinuxSSHDebugger
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string LinuxSSHDebuggerString = "445d9808-e09e-4ce1-bbf9-2628e1a70b65";
        public static Guid LinuxSSHDebugger = new Guid(LinuxSSHDebuggerString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int LinuxSSHDebuggerMenuGroup = 0x0001;
        public const int BuildPublishDebugCommand = 0x0100;
    }
}